- name: Gerar token com comando para join
  command: kubeadm token create --print-join-command
  delegate_to: k8s-master
  register: join_command
  run_once: true
  changed_when: false

- name: Adicionar o nós ao cluster
  command: "{{ join_command.stdout_lines[0] }}"
  register: join_cluster_result
  changed_when: join_cluster_result|search('This node has joined the cluster')

- name: Debug join_command
  debug:
    var: join_command

- name: Debug join_cluster_result
  debug:
    var: join_cluster_reult