- name: Verificar se o cluster já foi inicializado
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: node_already

- name: Gerar token com comando para join
  when: not node_already.stat.exists
  command: kubeadm token create --print-join-command
  delegate_to: k8s-master
  register: join_command
  run_once: true
  changed_when: false

- name: Adicionar o nós ao cluster
  when: not node_already.stat.exists
  command: "{{ join_command.stdout_lines[0] }}"
  register: join_cluster_result
  changed_when: join_cluster_result.stdout.find('This node has joined the cluster')
