---
- hosts: all
  become: yes
  gather_facts: yes
  remote_user: ubuntu

  roles:
  - k8s_common

- hosts: master
  become: yes
  gather_facts: yes
  remote_user: ubuntu

  roles:
  - k8s_master

- hosts: nodes
  become: yes
  gather_facts: yes
  remote_user: ubuntu

  roles:
  - k8s_nodes