---
- hosts: all
  become: true
  gather_facts: true
  remote_user: ubuntu

  roles:
  - k8s_common

- hosts: master
  become: true
  gather_facts: true
  remote_user: ubuntu

  roles:
  - k8s_master

- hosts: nodes
  become: true
  gather_facts: true
  remote_user: ubuntu

  roles:
  - k8s_nodes
