- name: Gerar token com comando para join
  command: kubeadm token create --print-join-command
  delegate_to: k8s-master
  register: join_command
  run_once: true

- name: Adicionar o nós ao cluster
  register: joing_cluster_result
  command: "{{ join_command.stdout_lines[0] }}"

- name: Debug join_command
  debug:
    var: join_command

- name: Debug join_cluster_result
  debug:
    var: join_cluster_reult