- name: Gerar token com comando para join
  command: kubeadm token create --print-join-command
  delegate_to: k8s-master
  register: join_command
  run_once: true

- name: debug
  debug:
    var: join_command.stdout_lines[0]

# - name: Copy join command to local file
#   copy:
#     content: "{{ join_command.stdout_lines[0] }}"
#     dest: "./join-command"
#   delegate_to: 127.0.0.1

- name: Adicionar o nós ao cluster
  shell: "{{ join_command.stdout_lines[0] }}"
