# - name: Install calico pod network
#   # become: false
#   command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml

- name: pod network
  shell: >
    set -o pipefail && \
    kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')
  register: weavenet
  args:
    executable: /bin/bash
  changed_when: '"created" in weavenet.stdout'