name: Kubernetes Demo - Azure
on:
  - push
  
  workflow_dispath:


jobs:

  Testes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
    
      - name: Ansible - Análise Estática
        run: |
          ansible-lint -v k8s-playbook.yml
