name: Kubernetes Demo on Azure
on:
  - push

jobs:
  testes:
    
    runs-on: ubuntu-latest
    
    steps:
    # - name: Check out
    #   uses: actions/checkout@v2
  
    # - name: Ansible lint
    #   uses: ansible/ansible-lint-action@master
    #   with:
    #     targets: "k8s-playbook.yml"

    - name: teste de comandos
      run: |
        whereis terraform
        whereis docker
        whereis ansible
        whereis packer
        whereis kubectl
        whereis make
      # if: ${{ always() }}
      
     
    # - name: Terraform validate
    #   run: make tf-validate
    
    # - name: Terraform plan
    #   run: make tf-plan
    #   env:
    #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    #     TF_VAR_ssh_pubkey: ${{ secrets.TF_VAR_SSH_PUBKEY }}
