name: Kubernetes Demo on Azure
on:
  - push

jobs:
  testes:
    
    runs-on: ubuntu-latest

    env:
      TF_VAR_SSH_PUBKEY = ${TF_VAR_SSH_PUBKEY}
    
    steps:
    - name: Check out
      uses: actions/checkout@v2
  
    - name: Ansible lint
      uses: ansible/ansible-lint-action@master
      with:
        targets: "k8s-playbook.yml"
  
    - name: Terraform init
      run: terraform init --upgrade=true
    
    - name: Terraform validate
      run: terraform validate
    
    - name: Terraform plan
      run: terraform plan
