name: Kubernetes Demo - Azure
on:
  - push
  - pull_request

jobs:
  testes:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
    
      - name: Ansible - Análise Estática
        uses: ansible/ansible-lint-action@master
        with:
          targets: ""