name: Kubernetes Demo - Azure
on: [push]

jobs:

  Lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
    
      - name: Listar diretorio
        run: |
          ansible-lint -v k8s-playbook.yml
