name: Kubernetes Demo - Azure
on:
  - push

jobs:

  Testes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
    
      - name: Ansible - Análise Estática
        uses: ansible/ansible-lint-action@151b9a2
